export type MeterHistoryType =   {
    "employeeName": string,
    "vendorId": string,
    "vendorName": string,
    "cardGuide": string,
    "isSynced": number,
    "statusCode": number,
    "statusDescription":string,
    "isDone": number,
    "insertedIn": string,
    "updatedIn": string,
    "doneDate": string,
    "barcode": string,
    "locationName": string,
    "buildingAdress": string,
    "latitude": string,
    "longitude": string,
    "installationWindow": string,
    "companyName": string,
    "mainCompany": string
  };